import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import HeaderPage from "~/components/layouts/header";
import SiderBar from "~/components/layouts/siderBar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="bg-custom_black_3 min-h-screen">
          <HeaderPage />
          <div className="flex">
            <SiderBar />
            <div className="w-full">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
